services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: powerview
    ports:
      - "8088:8088"
    volumes:
      - superset_data:/app/superset_home
      - ../data:/app/external_data # Change according to setting in the .env file
      - ../duckdb:/app/duckdb # Change according to setting in the .env file
      - ../../powerview:/app/powerview # Mount the powerview code for development
    environment:
      - SUPERSET_LOAD_EXAMPLES=no
      - DATABASE_DB=superset
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=superset
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:-superset}
      - DATABASE_DIALECT=postgresql

  db:
    image: postgres:13
    container_name: superset_db
    env_file: .env
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-superset}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  superset_data:
  db_data:
